### ISSUE TITLE
EPIC: Errbot tasks

### ISSUE THREAD

**Issue by rattboi** [BonnyCI/projman#174]
Seems like we've decided on using errbot for our irc bot solution. People like that it is written in python, and that it supports multiple backends such as slack, hipchat, and irc. 

- [x] Ansible role/playbook to install (https://github.com/BonnyCI/projman/issues/175)
- [x] Bot host provisioning (https://github.com/BonnyCI/projman/issues/176)
- [x] Create repo for errbot extensions (https://github.com/BonnyCI/projman/issues/170)
- [x] Create channel logging extension (https://github.com/BonnyCI/projman/issues/156)
- [ ] Pretty print the logs out into HTML (https://github.com/BonnyCI/projman/issues/202)
- [x] Create standup extension (https://github.com/BonnyCI/projman/issues/150)

**Comment by rattboi** [comment]
Made progress today on #175 and #176 . Hopefully I can test and get them reviewed tomorrow.

**Comment by mlangbehn** [comment]
Looks like #150 is done. Can we check it off and move it out of "In Progress?"
